---
# OPTIONAL TASKS (needed to run checks from the host machine)
# - name: Uncomment the GitLab IP whitelist line
#   replace:
#     path: /etc/gitlab/gitlab.rb
#     regexp: '^# (gitlab_rails\[''monitoring_whitelist''\] = \[.*)\]$'
#     replace: '\1, ''20.20.20.1'']'

# - name: Reconfigure GitLab
#   command: gitlab-ctl reconfigure

# - name: Restart unicorn
#   command: gitlab-ctl restart unicorn
#   retries: 2
# END OF OPTIONAL TASKS

- name: Check nodejs application health
  uri:
    url: http://localhost:8080/-/health
    return_content: yes
  # Register the output of the module in a variable
  register: nodejsapk_health

- name: Print nodejsapk health
  debug:
    msg: "{{ nodejsapk_health.content }}"

# Run the 2 other kind of health checks below
